allergies:
  label: 'csatar.csatar::lang.plugin.admin.allergy.allergy'
  view:
    list: $/csatar/csatar/models/allergy/columnsPivot.yaml
    toolbarButtons: add|remove|create
  manage:
    form: $/csatar/csatar/models/allergy/fields.yaml
  pivot:
    form: $/csatar/csatar/models/allergy/fieldsPivot.yaml
    