list: $/csatar/csatar/models/teamreport/columns.yaml
modelClass: Csatar\Csatar\Models\TeamReport
title: 'csatar.csatar::lang.plugin.admin.teamReport.teamReports'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'csatar/csatar/teamreports/update/:id'
