scouts:
  label: 'csatar.csatar::lang.plugin.admin.scout.scouts'
  view:
    list: $/csatar/csatar/models/teamreport/scoutColumns.yaml
    toolbarButtons: false
    defaultSort:
      column: 'pivot[name]'
      direction: asc
ageGroups:
    label: 'csatar.csatar::lang.plugin.admin.ageGroups.ageGroups'
    view:
        list: $/csatar/csatar/models/teamreport/ageGroupColumns.yaml
        toolbarButtons: false
