name: 'csatar.csatar::lang.plugin.admin.teamReport.teamReport'
form: $/csatar/csatar/models/teamreport/fields.yaml
modelClass: Csatar\Csatar\Models\TeamReport
defaultRedirect: csatar/csatar/teamreports
create:
    redirect: 'csatar/csatar/teamreports/update/:id'
    redirectClose: csatar/csatar/teamreports
update:
    redirect: csatar/csatar/teamreports
    redirectClose: csatar/csatar/teamreports
