list: $/csatar/csatar/models/agegroup/columns.yaml
modelClass: Csatar\Csatar\Models\AgeGroup
title: 'csatar.csatar::lang.plugin.admin.ageGroups.ageGroups'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'csatar/csatar/agegroups/update/:id'
