name: 'csatar.csatar::lang.plugin.admin.mandate.mandate'
form: $/csatar/csatar/models/mandate/fields.yaml
modelClass: Csatar\Csatar\Models\Mandate
defaultRedirect: csatar/csatar/mandates
create:
    redirect: 'csatar/csatar/mandates/update/:id'
    redirectClose: csatar/csatar/mandates
update:
    redirect: csatar/csatar/mandates
    redirectClose: csatar/csatar/mandates
