name: 'csatar.csatar::lang.plugin.admin.trainingQualification.trainingQualification'
form: $/csatar/csatar/models/trainingqualification/fields.yaml
modelClass: Csatar\Csatar\Models\TrainingQualification
defaultRedirect: csatar/csatar/trainingqualifications
create:
    redirect: 'csatar/csatar/trainingqualifications/update/:id'
    redirectClose: csatar/csatar/trainingqualifications
update:
    redirect: csatar/csatar/trainingqualifications
    redirectClose: csatar/csatar/trainingqualifications
