list: $/csatar/csatar/models/specialtest/columns.yaml
modelClass: Csatar\Csatar\Models\SpecialTest
title: 'csatar.csatar::lang.plugin.admin.specialTest.specialTests'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'csatar/csatar/specialtests/update/:id'
