list: $/csatar/csatar/models/chronicillness/columns.yaml
modelClass: Csatar\Csatar\Models\ChronicIllness
title: 'csatar.csatar::lang.plugin.admin.chronicIllness.chronicIllnesses'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'csatar/csatar/chronicillnesses/update/:id'
