list: $/csatar/csatar/models/leadershipqualification/columns.yaml
modelClass: Csatar\Csatar\Models\LeadershipQualification
title: 'csatar.csatar::lang.plugin.admin.leadershipQualification.leadershipQualification'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'csatar/csatar/leadershipqualifications/update/:id'
