troops:
  label: 'csatar.csatar::lang.plugin.admin.troop.troop'
  view:
    list: $/csatar/csatar/models/troop/columns.yaml
    toolbarButtons: create|delete
  manage:
    form: $/csatar/csatar/models/troop/fields.yaml
patrols:
  label: 'csatar.csatar::lang.plugin.admin.patrol.patrol'
  view:
    list: $/csatar/csatar/models/patrol/columns.yaml
    toolbarButtons: create|delete
  manage:
    form: $/csatar/csatar/models/patrol/fields.yaml
mandates:
  label: 'csatar.csatar::lang.plugin.admin.mandate.mandate'
  view:
    list: $/csatar/csatar/models/mandate/columns.yaml
    toolbarButtons: create|delete
  manage:
    form: $/csatar/csatar/models/mandate/fields.yaml
galleries:
    label: 'csatar.csatar::lang.plugin.admin.gallery.gallery'
    view:
        list: $/pollozen/simplegallery/models/gallery/columns.yaml
        toolbarButtons: add|remove|create
    manage:
        list: $/pollozen/simplegallery/models/gallery/columns.yaml
        form:
            fields:
                name:
                    span: auto
                    label: pollozen.simplegallery::lang.column.name
                    required: true
                slug:
                    span: auto
                    label: Slug
                    preset: name
                    required: true
                description:
                    span: full
                    label: pollozen.simplegallery::lang.column.description
                images:
                    label: pollozen.simplegallery::lang.column.images
                    type: fileupload
                    mode: image
                pivot[model_type]:
                    type: text
                    label: 'model type'
                    default: 'Csatar\Csatar\Models\Team'
                    readOnly: 1
    pivot:
        form:
            fields:
                'pivot[model_type]':
                    type: text
                    label: 'model type'
                    default: 'Csatar\Csatar\Models\Team'
                    readOnly: 1
