troops:
  label: 'csatar.csatar::lang.plugin.admin.troop.troop'
  view:
    list: $/csatar/csatar/models/troop/columns.yaml
    toolbarButtons: create|delete
  manage:
    form: $/csatar/csatar/models/troop/fields.yaml
patrols:
  label: 'csatar.csatar::lang.plugin.admin.patrol.patrol'
  view:
    list: $/csatar/csatar/models/patrol/columns.yaml
    toolbarButtons: create|delete
  manage:
    form: $/csatar/csatar/models/patrol/fields.yaml
mandates:
  label: 'csatar.csatar::lang.plugin.admin.mandate.mandate'
  view:
    list: $/csatar/csatar/models/mandate/columns.yaml
    toolbarButtons: create|delete
  manage:
    form: $/csatar/csatar/models/mandate/fields.yaml
scouts:
    label: 'csatar.csatar::lang.plugin.admin.scout.scouts'
    view:
        list: $/csatar/csatar/models/scout/columns.yaml
        toolbarButtons: create
    manage:
        form: $/csatar/csatar/models/scout/fields.yaml
