name: 'csatar.csatar::lang.plugin.admin.trainings.trainings'
form: $/csatar/csatar/models/training/fields.yaml
modelClass: Csatar\Csatar\Models\Training
defaultRedirect: csatar/csatar/trainings
create:
    redirect: 'csatar/csatar/trainings/update/:id'
    redirectClose: csatar/csatar/trainings
update:
    redirect: csatar/csatar/trainings
    redirectClose: csatar/csatar/trainings
