list: $/csatar/csatar/models/allergy/columns.yaml
modelClass: Csatar\Csatar\Models\Allergy
title: 'csatar.csatar::lang.plugin.admin.allergy.allergies'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'csatar/csatar/allergies/update/:id'
