list: $/csatar/csatar/models/tshirtsize/columns.yaml
modelClass: Csatar\Csatar\Models\TShirtSize
title: 'csatar.csatar::lang.plugin.admin.tShirtSize.tShirtSize'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'csatar/csatar/tshirtsizes/update/:id'
