mandates:
  label: 'csatar.csatar::lang.plugin.admin.mandate.mandate'
  view:
    list: $/csatar/csatar/models/mandate/columns.yaml
    toolbarButtons: create|delete
  manage:
    form: $/csatar/csatar/models/mandate/fields.yaml
