name: 'csatar.csatar::lang.plugin.admin.troop.troop'
form: $/csatar/csatar/models/troop/fields.yaml
modelClass: Csatar\Csatar\Models\Troop
defaultRedirect: csatar/csatar/troops
create:
    redirect: 'csatar/csatar/troops/update/:id'
    redirectClose: csatar/csatar/troops
update:
    redirect: csatar/csatar/troops
    redirectClose: csatar/csatar/troops
