list: $/csatar/csatar/models/mandatetype/columns.yaml
modelClass: Csatar\Csatar\Models\MandateType
title: 'csatar.csatar::lang.plugin.admin.mandateType.mandateTypes'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'csatar/csatar/mandatetypes/update/:id'
showTree: 1
treeExpanded: 1
