title: Associations
modelClass: Csatar\Csatar\Models\Association
list: $/csatar/csatar/models/association/columns.yaml
recordUrl: 'csatar/csatar/associations/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
