districts:
  label: 'csatar.csatar::lang.plugin.admin.district.district'
  view:
    list: $/csatar/csatar/models/district/columns.yaml
    toolbarButtons: create|delete
  manage:
    form: $/csatar/csatar/models/district/fields.yaml
legal_relationships:
  label: 'csatar.csatar::lang.plugin.admin.legalRelationship.legalRelationship'
  view:
    list: $/csatar/csatar/models/legalrelationship/columnsPivot.yaml
    toolbarButtons: add|remove
  manage:
    list: $/csatar/csatar/models/legalrelationship/columns.yaml
    form: $/csatar/csatar/models/legalrelationship/fields.yaml
  pivot:
    form: $/csatar/csatar/models/legalrelationship/fieldsPivot.yaml
mandates:
  label: 'csatar.csatar::lang.plugin.admin.mandate.mandate'
  view:
    list: $/csatar/csatar/models/mandate/columns.yaml
    toolbarButtons: create|delete
  manage:
    form: $/csatar/csatar/models/mandate/fields.yaml
galleries:
    label: 'csatar.csatar::lang.plugin.admin.gallery.gallery'
    view:
        list: $/pollozen/simplegallery/models/gallery/columns.yaml
        toolbarButtons: add|remove|create
    manage:
        list: $/pollozen/simplegallery/models/gallery/columns.yaml
        form:
            fields:
                name:
                    span: auto
                    label: pollozen.simplegallery::lang.column.name
                    required: true
                slug:
                    span: auto
                    label: Slug
                    preset: name
                    required: true
                description:
                    span: full
                    label: pollozen.simplegallery::lang.column.description
                images:
                    label: pollozen.simplegallery::lang.column.images
                    type: fileupload
                    mode: image
                pivot[model_type]:
                    type: text
                    label: 'model type'
                    default: 'Csatar\Csatar\Models\Association'
                    readOnly: 1
    pivot:
        form:
            fields:
                'pivot[model_type]':
                    type: text
                    label: 'model type'
                    default: 'Csatar\Csatar\Models\Association'
                    readOnly: 1
