districts:
  label: 'csatar.csatar::lang.plugin.admin.district.district'
  view:
    list: $/csatar/csatar/models/district/columns.yaml
    toolbarButtons: create|delete
  manage:
    form: $/csatar/csatar/models/district/fields.yaml
legal_relationships:
  label: 'csatar.csatar::lang.plugin.admin.legalRelationship.legalRelationship'
  view:
    list: $/csatar/csatar/models/legalRelationship/columnsPivot.yaml
    toolbarButtons: add|remove
  manage:
    list: $/csatar/csatar/models/legalRelationship/columns.yaml
    form: $/csatar/csatar/models/legalRelationship/fields.yaml
  pivot:
    form: $/csatar/csatar/models/legalRelationship/fieldsPivot.yaml
