plugin:
    name: CSATÁR
    description: 'Plugin for the RMCSSZ''s CSATÁR project'
    author: 'CSATÁR team'
    icon: icon-leaf
    homepage: ''
navigation:
    main-menu-item-scout-system-data:
        label: 'Scout System Data'
        url: /
        icon: icon-sitemap
        sideMenu:
            side-menu-legal-relationship-categories:
                label: 'Legal Relationship Categories'
                url: csatar/csatar/legalrelationships
                icon: icon-sitemap
            side-menu-chronic-illness-categories:
                label: 'Chronic Illness Categories'
                url: /csatar/csatar/chronicillnesses
                icon: icon-sitemap
            side-menu-allergy-categories:
                label: 'Allergy Categories'
                url: csatar/csatar/allergies
                icon: icon-sitemap
            side-menu-special-item-categories:
                label: 'Special Diet Categories'
                url: csatar/csatar/specialdiets
                icon: icon-sitemap
            side-menu-religion-categories:
                label: 'Religion Categories'
                url: csatar/csatar/religions
                icon: icon-sitemap
            side-menu-tshirt-size-categies:
                label: 'T-Shirt Size Categories'
                url: csatar/csatar/tshirtsizes
                icon: icon-sitemap
    main-menu-scout-data:
        label: 'Scout Data'
        url: /csatar/csatar/scouts
        icon: icon-bell
