plugin:
    name: 'csatar.csatar::lang.plugin.name'
    description: 'csatar.csatar::lang.plugin.description'
    author: 'csatar.csatar::lang.plugin.author'
    icon: icon-leaf
    homepage: ''
navigation:
    main-menu-item-organization-system-data:
        label: 'csatar.csatar::lang.plugin.admin.admin.menu.organizationSystemData.organizationSystemData'
        url: /
        icon: icon-sitemap
        sideMenu:
            side-menu-item-hierarchy:
                label: 'csatar.csatar::lang.plugin.admin.admin.menu.organizationSystemData.hierarchy'
                url: csatar/csatar/hierarchy
                icon: icon-sitemap
            side-menu-item-associations:
                label: 'csatar.csatar::lang.plugin.admin.association.associations'
                url: /csatar/csatar/associations
                icon: icon-sitemap
            side-menu-item-districts:
                label: 'csatar.csatar::lang.plugin.admin.district.districts'
                url: csatar/csatar/districts
                icon: icon-sitemap
            side-menu-item-teams:
                label: 'csatar.csatar::lang.plugin.admin.team.teams'
                url: csatar/csatar/teams
                icon: icon-sitemap
    main-menu-item-scout-system-data:
        label: 'csatar.csatar::lang.plugin.admin.admin.menu.scoutSystemData.scoutSystemData'
        url: /
        icon: icon-sitemap
        sideMenu:
            side-menu-legal-relationship-categories:
                label: 'csatar.csatar::lang.plugin.admin.admin.menu.scoutSystemData.legalRelationshipCategories'
                url: csatar/csatar/legalrelationships
                icon: icon-sitemap
            side-menu-chronic-illness-categories:
                label: 'csatar.csatar::lang.plugin.admin.admin.menu.scoutSystemData.chronicIllnessCategories'
                url: /csatar/csatar/chronicillnesses
                icon: icon-sitemap
            side-menu-allergy-categories:
                label: 'csatar.csatar::lang.plugin.admin.admin.menu.scoutSystemData.allergyCategories'
                url: csatar/csatar/allergies
                icon: icon-sitemap
            side-menu-special-item-categories:
                label: 'csatar.csatar::lang.plugin.admin.admin.menu.scoutSystemData.specialDietCategories'
                url: csatar/csatar/specialdiets
                icon: icon-sitemap
            side-menu-religion-categories:
                label: 'csatar.csatar::lang.plugin.admin.admin.menu.scoutSystemData.religionCategories'
                url: csatar/csatar/religions
                icon: icon-sitemap
            side-menu-tshirt-size-categies:
                label: 'csatar.csatar::lang.plugin.admin.admin.menu.scoutSystemData.tShirtSizeCategories'
                url: csatar/csatar/tshirtsizes
                icon: icon-sitemap
    main-menu-scout-data:
        label: 'csatar.csatar::lang.plugin.admin.admin.menu.scout'
        url: /csatar/csatar/scouts
        icon: icon-bell
