list: $/csatar/csatar/models/specialdiet/columns.yaml
modelClass: Csatar\Csatar\Models\SpecialDiet
title: 'csatar.csatar::lang.plugin.admin.specialDiet.specialDiets'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'csatar/csatar/specialdiets/update/:id'
